# Простой конфигурационный файл для Jekyll

# Указываем, что исходная директория - это корень проекта
source: src

# Директория для сгенерированного сайта (по умолчанию _site)
destination: ./_site

# Устанавливаем базовые параметры
title: "Мой сайт"
description: "Простой сайт на Jekyll"
url: "http://example.com"

# Отключаем использование SCSS
sass:
  style: compressed
  load_paths: []

# Не используем плагины, если они не нужны
plugins: []

# Отключаем автоматическую генерацию страниц, если они не требуются
paginate: 10
