version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform:
  - x64
build_script:
  - yarn install
  - yarn run build
deploy:
  provider: GitHub
  auth_token: GITHUB_TOKEN
  repository: Mikhail5509/goblin-game # замените на ваше имя пользователя и название репозитория
  branch: master
  on_success: true
